name: Deploy Infrastructure

on: workflow_dispatch

env:
  INFRASTRUCTURE_DIRECTORY: "./infrastructure"
  SCRIPTS_DIRECTORY: "./scripts"

jobs:
  deploy:
    name: Validate & Deploy Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup Terraform configuration
        working-directory: ${{ env.SCRIPTS_DIRECTORY }}
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_TERRAFORM_BUCKET: ${{ secrets.AWS_TERRAFORM_BUCKET }}
          AWS_GLOBAL_CONFIGURATION_BUCKET: ${{ secrets.AWS_GLOBAL_CONFIGURATION_BUCKET }}
        run: sh setup-configuration.sh

      - name: Terraform Init
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: terraform apply -auto-approve